# Generated by Django 4.2.29 on 2026-03-13 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_phone', models.CharField(max_length=15)),
                ('receiver_name', models.CharField(max_length=200)),
                ('receiver_phone', models.CharField(max_length=15)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=6)),
                ('tracking_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('loaded', 'Loaded'), ('in_transit', 'In Transit'), ('arrived', 'Arrived'), ('collected', 'Collected')], default='booked', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybills', to='booking.trip')),
            ],
        ),
        migrations.CreateModel(
            name='WaybillStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('loaded', 'Loaded'), ('in_transit', 'In Transit'), ('arrived', 'Arrived'), ('collected', 'Collected')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('waybill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='waybill.waybill')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
